/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import org.junit.Test;
import static org.junit.Assert.assertNotNull;

public class AppTest {

    @Test
    public void testAppInstance() {
        App classUnderTest = new App();
        assertNotNull("App instance should not be null", classUnderTest);
    }
}
